### ISSUE TITLE
BeautifulSoup

### ISSUE THREAD

**Issue by okotaku** [okotaku/pystudy#1]
以下のコードのBeautifulSoupの処理がうまくいきません。
対応策お願いします。
https://github.com/okotaku/pystudy/blob/master/codecheck.ipynb

**Comment by Koekuwa** [comment]
一番下のところ

    soup = BeautifulSoup(html,"html5lib")  
    h1 = soup.result.doc.id.string  
    print(h1)
こんな感じ出いける感ある，多分htmlじゃなくて文章がxml形式やから問題？
